-- liquibase formatted sql

--changeset vcharushnikov:1
CREATE TABLE socks
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color TEXT    NOT NULL,
    cotton_Part INTEGER,
    quantity INTEGER
);